// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfIsInstalled():Promise<boolean>;

export function Test(arg1:string):Promise<string>;
