// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfIsInstalled() {
  return window['go']['backend']['App']['CheckIfIsInstalled']();
}

export function GenerateConfig(arg1) {
  return window['go']['backend']['App']['GenerateConfig'](arg1);
}

export function GetAllVmsStats() {
  return window['go']['backend']['App']['GetAllVmsStats']();
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}
