// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckIfIsInstalled():Promise<boolean>;

export function GenerateConfig(arg1:string):Promise<backend.Config>;

export function TestConnection(arg1:string):Promise<boolean>;
