// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIfIsInstalled() {
  return window['go']['backend']['App']['CheckIfIsInstalled']();
}

export function Test(arg1) {
  return window['go']['backend']['App']['Test'](arg1);
}
